version: "3"

volumes:
  node_modules:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - "3000:3000"
    volumes:
      - .:/webapp
      - /webapp/node_modules